Post Timeout configurable through Env with 60 segs as default
valiot/pygqlc pull request #22
Opened 2022-01-25 03:54 UTC by alde103

# Description

The `request` library should use a timeout for every request, otherwise there is a possibility that the process will wait indefinitely for a response from a server.

Therefore, this new feature adds the ability to configure the post_timeout through environment variables, having 60 seconds as default.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
tests/pygqlc/test_environments.py

![2022-01-24_21-33](https://user-images.githubusercontent.com/18536836/150907834-6663af44-2d45-42b3-a6a8-6e30b5e25f12.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-26 17:16 UTC, acrogenesis requested changes

2022-01-26 17:16 UTC, acrogenesis commented on tests/conftest.py
> +  post_timeout_str = (os.environ.get('POST_TIMEOUT') or '10')
Aquí debería ser 60 no?

2022-01-26 17:34 UTC, alde103 commented on tests/conftest.py
> +  post_timeout_str = (os.environ.get('POST_TIMEOUT') or '10')
Ese es para la configuración de los test, según yo no impacta  ya que en el src si lo tiene 60, pero si quieren lo puedo cambiar

2022-01-26 17:42 UTC, acrogenesis approved these changes
Lo veo bien mas creo que ocupamos a baruc para el publish a pip. ( es algo que debiéramos automatizar @barucAlmaguer )

2022-02-04 16:26 UTC, barucAlmaguer approved these changes
se ve bien 🤓

2022-02-04 17:01 UTC, merged